<div class="has_header" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="page_title" message="message"></sb-header>

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

    <div class="list l3">
        <div class="filters padding subheader" ng-show="places.length">
            <div>
                <div class="listing toggle" ng-show="filter.show">
                    <ul>
                        <li class="search" ng-click="filter.by('search');" ng-style="filter.search.picto" ng-class="{border: search}"><?php echo $this->_("Search"); ?></li>
                        <li class="status" ng-click="filter.by('status');" ng-style="filter.status.picto" ng-class="{border: filter.status.current.status_id}"><?php echo $this->_("Type"); ?></li>
                        <li class="label" ng-click="filter.by('label');" ng-style="filter.label.picto" ng-class="{border: filter.label.current.label_id}"><?php echo $this->_("Label"); ?></li>
                        <li class="geolocation" ng-click="filter.by('geolocation');" ng-style="filter.geolocation.picto" ng-class="{border: filter.geolocation.use_geolocation}"><?php echo $this->_("Geolocation"); ?></li>
                    </ul>
                </div>
                <div class="slide-left back filter" ng-show="!filter.show">
                    <button type="button" class="btn_left header no-background" ng-click="filter.reset();">
                        <div class="back_arrow subheader"></div>
                    </button>
                </div>
                <div class="search slide-right filter" ng-show="filter.search.is_visible">
                    <form ng-submit="search = search_tmp">
                        <input type="text" class="full_width left" ng-model="search_tmp" placeholder="<?php echo $this->_("Search"); ?>" />
                        <button type="submit" class="subheader reverse right"><?php echo $this->_("OK"); ?></button>
                    </form>
                </div>
                <div class="status slide-right filter" ng-show="filter.status.is_visible">
                    <div class="segmented_control ios">
                        <button class="subheader element" ng-repeat="status in filter.status.list" ng-click="filter.status.set(status);" ng-class="{reverse: filter.status.current == status, first: $index==0, last: $index == filter.status.list.length - 1}">
                            {{ status.name }}
                        </button>
                    </div>
                </div>
                <div class="label slide-right filter" ng-show="filter.label.is_visible">
                    <div class="segmented_control ios right">
                        <button class="subheader element" ng-repeat="label in filter.label.list" ng-click="filter.label.set(label);" ng-class="{reverse: filter.label.current == label, first: $index==0, last: $index == filter.label.list.length - 1}">
                            <img ng-src="{{ label.picto }}" height="99%" />
                        </button>
                    </div>
                </div>
                <div class="geolocation slide-right filter" ng-show="filter.geolocation.is_visible">
                    <label class="left"><?php echo $this->_("See the places close to me"); ?></label>
                    <div class="segmented_control ios right">
                        <button class="subheader element first" ng-click="filter.geolocation.set(true);" ng-class="{reverse: filter.geolocation.use_geolocation}">Oui</button>
                        <button class="subheader element last" ng-click="filter.geolocation.set(false);" ng-class="{reverse: !filter.geolocation.use_geolocation}">Non</button>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <ul>
            <li class="arrow_right slide-left" ng-repeat="place in places | filter:search | placesByLabel:filter.label.current | placesByStatus:filter.status.current | orderBy:'distance':false | limitTo:filter.limitTo" ng-class="{first: $index == 0, has_picture: place.picture_url }" ng-click="showPlace(place)" ng-hide="place.is_hidden">
                <div class="left picture" image-src="place.picture_url" ng-if="place.picture_url" sb-image></div>
                <div class="details padding" ng-class="{has_picture: place.picture_url, has_label: place.label_id}">
                    <h3 class="title">{{ place.name }}</h3>
                    <div class="distance" ng-if="place.distance">
                        <span class="block"><?php echo $this->_("Distance:"); ?> {{ place.distance }} km</span>
                    </div>
                    <div class="address">
                        <span class="block">{{ place.street }}</span>
                        <span class="block">{{ place.postcode }} {{ place.city }}</span>
                    </div>
                    <div class="label">
                        <img ng-src="place.label_img_src" height="20px" ng-if="place.label_img_src" />
                    </div>
                    <div class="clear"></div>
                </div>
            </li>
            <li class="empty" ng-if="!places.length">
                <p class="a-center"><?php echo $this->_("Nothing to display"); ?></p>
            </li>
        </ul>
    </div>

</div>