<?php $application = $this->getApplication(); ?>
<?php $value = $this->getOptionValue(); ?>
<?php $place = new Place_Model_Place(); ?>
<?php $places = $place->findAll(array('value_id' => $value->getId())); ?>
<div class="edit_page place">
    <div class="form_content">
        <div id="list" class="">

            <div class="section">
                <h4 class="subtitle">
                    <span class="left area"><?php echo $this->_('Upload'); ?></span>
                    <hr class="area reverse">
                    <div class="clear"></div>
                </h4>
                <div>
                    <div>
                        <!--[if gte IE 10]><!-->
                        <button id="upload_places" type="button" class="upload editor_menu active image_left">
                            <i class="icon-camera-retro"></i>
                            <?php echo $this->_("Upload a<br />File"); ?>
                        </button>
                        <!--<![endif]-->
                        <input id="file_uploader" style="display:none" type="file" name="files[]" data-url="<?php echo $this->getUrl('place/application/upload'); ?>">
                    </div>
                </div>
            </div>

            <?php /*
            <div class="section">
                <h4 class="subtitle">
                    <span class="left area"><?php echo $this->_('Add'); ?></span>
                    <hr class="area reverse">
                    <span class="area right">
                        <button type="button" onclick="feature.edit()" class="default_button add right" id="add_item">
                            <i class="icon-plus"></i>
                        </button>
                    </span>
                    <div class="clear"></div>
                </h4>
                <?php echo $this->createPartialHtml('no_item', 'core_view_default', 'application/customization/features/edit/no_item.phtml'); ?>
            </div>
            */ ?>
            <?php if ($places->count()) : ?>
            <div class="section">
                <h4 class="subtitle">
                    <span class="left area"><?php echo $this->_('Manage'); ?></span>
                    <hr class="area reverse">
                    <span class="area right">
                        <button type="button" class="default_button" id="toggle_existing_items">
                            <i class="icon-chevron-down"></i>
                        </button>
                    </span>
                    <div class="clear"></div>
                </h4>
                <div id="existing_items" class="none">

                    <table id="table_places_list" width="615px">
                        <colgroup>
                            <col width="15%">
                            <col width="40%">
                            <col width="40%">
                            <col width="5%">
                        </colgroup>
                        <thead>
                        <tr class="a-left">
                            <th><?php echo $this->_("Identifier"); ?></th>
                            <th><?php echo $this->_("Name"); ?></th>
                            <th><?php echo $this->_("City"); ?></th>
                            <th></th>
                            <th class="none"><?php echo $this->_("Status"); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($places as $k => $place) : ?>
                            <tr class="place" rel="<?php echo $place->getId() ?>">
                                <td><?php echo $place->getIdentifier() ?></td>
                                <td><?php echo $place->getName(); ?></td>
                                <td><?php echo $place->getCity(); ?></td>
                                <td align="center"><i class="edit_place icon-edit"></i></td>
                                <td class="none"><?php echo $place->getStatus(); ?></td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                        <tfoot>
                        <tr class="a-left">
                            <th><?php echo $this->_("Identifier"); ?></th>
                            <th><?php echo $this->_("Name"); ?></th>
                            <th><?php echo $this->_("City"); ?></th>
                            <th></th>
                            <th class="none"><?php echo $this->_("Status"); ?></th>
                        </tr>
                        </tfoot>
                    </table>

                    <div class="clear"></div>
                </div>
            </div>
            <?php endif; ?>

            <div class="section">
                <?php echo $this->getLayout()
                        ->addPartial('background_image', 'Core_View_Default', 'application/customization/features/edit/background_image.phtml')
                        ->setValueId($value->getId())
                        ->toHtml()
                    ;
                ?>
            </div>

        </div>
        <div id="edit" class="" style="display: none;">
            <?php /*
            <h4 class="subtitle">
                <span class="left area"><?php echo $this->_('Editing'); ?></span>
                <hr class="area reverse">
                <div class="clear"></div>
            </h4>
            <div class="block">
                <form id="newsCreateForm" action="<?php echo $this->getUrl('comment/application/editpost') ?>" method="post">
                    <div class="buttons">
                        <button type="button" onclick="page.reload()" class="delete left"><i class="icon-arrow-left"></i></button>
                        <button type="submit" class="default_button right">OK</button>
                        <div class="clear"></div>
                    </div>
                    <input type="hidden" name="value_id" value="<?php echo $value->getId(); ?>" />
                    <div>
                        <p class="subtitle" data-tip="9"><label class="block"><?php echo $this->_('Create a news:'); ?></label></p>
                        <textarea style="width:98%; height: 100px;" id="title" name="text" class="required input border" rows="3" cols="95" maxlength="255"></textarea>
                    </div>
                    <br />
                    <div>
                        <!--[if gte IE 10]><!-->
                        <button  type="button" class="upload_comment_picture upload editor_menu active image_left">
                            <i class="icon-camera-retro"></i>
                            <?php echo $this->_('Insert a'); ?><br>
                            <span data-tip="10" class="bold"><?php echo $this->_('picture'); ?></span>
                        </button>
                        <!--<![endif]-->
                        <input class="uploader_comment" style="display:none" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
                        <div id="uploaded_content"></div>
                    </div>
                    <br />
                    <input type="hidden" name="option_value_id" value="<?php echo $value->getId(); ?>" />
                    <input type="hidden" id="image_actus" name="image" value="" />
                </form>
            </div>
            */ ?>
        </div>

        <script type="text/javascript">

                page.setCallback("willappear", function() {
                    $('#table_places_list').dataTable({
                        asStripeClasses: ['odd editor_menu active', 'even'],
                        bLengthChange: false,
                        bFilter: false,
                        sPaginationType: "full_numbers",
                        fnDrawCallback: function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {

//                            $.each(nRow.aoData, function(i, el) {
//
//                                var tr = $(el.nTr);
//
//                                tr.unbind('mouseenter mouseleave').hover(function() {
//                                    $(this).addClass('reverse');
//                                }, function() {
//                                    $(this).removeClass('reverse');
//                                });
//                                tr.unbind('click');
//                                this.bindEditOrder(tr);
//
//                            }.bind(this));


                        }.bind(this),
                        fnCreatedRow: function( nRow, aData, iDataIndex ) {
                            var order_id = $(nRow).attr('rel');
                            $(nRow).children('td').each(function(i) {
                                if(!$(this).attr('id')) {
                                    var id = 'order_'
                                    switch(i) {
                                        case 0: id+='number';break;
                                        case 1: id+='status';break;
                                        case 2: id+='customer_name';break;
                                        case 3: id+='total';break;
                                    }
                                    $(this).attr('id', id+'_'+order_id);

                                }
                            });

                        }
                    });
                });
                page.setCallback('didappear', function() {

                    $('#toggle_existing_items').click(function() {
                        $('#existing_items').stop().slideToggle(300, function() {
                            if($(this).is(':visible')) $('#toggle_existing_items').children('i').removeClass('icon-chevron-down').addClass('icon-chevron-up');
                            else $('#toggle_existing_items').children('i').removeClass('icon-chevron-up').addClass('icon-chevron-down')
                        });
                    });

                    $('#upload_places').click(function() {
                        $('#file_uploader').trigger('click');
                        return false;
                    });

                    $('.delete_comment').click(function() {
                        var id = $(this).attr('rel');
                        reload($(this), '<?php echo $this->getUrl('comment/application/delete'); ?>/id/'+id, true, function(datas) {
                            if(datas.success) {
                                page.reload();
                            }
                        });
                    });

                    $('.hide_comment').click(function() {
                        var id = $(this).attr('rel');
                        reload($(this), '<?php echo $this->getUrl('comment/application/hide'); ?>/id/'+id, true, function(datas) {
                            if(datas.success) {
                                page.reload();
                            }
                        });
                    });

                    $('.show_comment').click(function() {
                        var id = $(this).attr('rel');
                        reload($(this), '<?php echo $this->getUrl('comment/application/show'); ?>/id/'+id, true, function(datas) {
                            if(datas.success) {
                                page.reload();
                            }
                        });
                    });

                });

                page.setCallback('willdisappear', function() {
                    $('#toggle_existing_items').unbind('click');
                    $('#newsCreateForm').unbind('submit');
                    $('.news_actions').unbind('mouseenter mouseout');
                    $('.delete_comment').unbind('click');
                    $("#table_places_list").dataTable().fnDestroy();
                });

                var place_uploader = new Uploader();
                $('#file_uploader').fileupload({
                    dataType: 'json',
                    formData: {value_id: "<?php echo $value->getId(); ?>"},
                    add: function(e, data) {
                        data.submit();
                        place_uploader.showProgressbar();
                    },
                    progressall: function(e, data) {
                        place_uploader.moveProgressbar(data);
                    },
                    done: function(e, data) {
                        if (data.result.error) {
                            loader.hide();
                            place_uploader.showError(data.result.message);
                        }
                        else if (data.result.success) {

                            place_uploader.showSuccess("<?php echo $this->_("Indexing data... This process may take few minutes. Please, do not refresh the page."); ?>");
                            loader.hide();
                            reload($("#file_uploader"), "<?php echo $this->getUrl("place/application/updatelocations", array("value_id" => $value->getId())); ?>", true, function(data) {
                                if(data.success) {
                                    loader.hide();
                                    place_uploader.showSuccess(data.success_message);
                                    message.setTimer(4);
                                    page.reload();
                                }
                            }, function() {
                                place_uploader.hide();
                            });
                        }
                    }
                });

        </script>
        <style>
            .customization .area.details {margin: 0;}
            #logo_edit {display: none;}
            #compte_facebook {display: block;}
            .news_actions .title {width: 85% !important;}
            .news_actions {padding: 10px 0;}
            .news_actions.hidden .title, .news_actions.hidden .icon {opacity:0.5}
            .news_actions.hidden .icon:hover {opacity:1}
            div#list a.icon, div#list span.price {margin-top: 0;}
            #uploaded_content {margin-top:20px;}


            .place table.dataTable {
                margin: 20px 0 10px;
            }
            .place table.dataTable tr th, .place table.dataTable tr td {
                padding: 7px 5px;
            }
            .place table.dataTable thead tr {
                border-bottom: 2px double white;
            }
            .place table.dataTable tfoot tr {
                border-top: 2px double white;
            }
            .place table.dataTable th, .place table.dataTable td {
                padding: 10px;
            }
            .place table.dataTable th {
                text-align: left;
            }
            .place .dataTables_info {
                float: left;
                padding: 10px;
            }
            .place .dataTables_paginate {
                float: right;
            }
            .place .dataTables_paginate a {
                display: block;
                float: left;
                padding: 10px 5px;
            }
            .place .dataTables_paginate a.paginate_button_disabled {
                opacity: 0.3
            }

        </style>
    </div>
    <div class="clear"></div>
</div>
