<?php $isLoggedIn = $this->getSession()->isLoggedIn('customer'); ?>
<?php $customer = $this->getSession()->getCustomer(); ?>
<div id="customer_account" class="customer_account background">
    <div class="forgotpassword" id="forgotpassword">
        <?php if($this->isMobileDevice()) : ?>

        <div id="forgot_password" class="forgot_password">
            <form name="forgotPasswordForm" id="forgotPasswordForm" class="accountForm" method="post" action="<?php echo $this->getUrl('customer/mobile_account/forgotpasswordpost'); ?>">
                <div class="form">
                    <div class="form_content align-center">
                        <br />
                        <div>
                            <p><?php echo $this->_("Please enter your email address. We\'ll send you your password right now.") ?></p>
                        </div>
                        <br />
                        <div class="padding">
                            <input type="email" value="" class="required email full_width" placeholder="<?php echo $this->_("Email") ?>" name="email" id="forgotpassword_email" />
                        </div>
                    </div>
                </div>
                <button type="submit" style="display:none;"></button>
            </form>
        </div>

        <script type="text/javascript">

            var subpage = page.getSubpage('customer_account_forgotpassword');

            subpage.setCallback('willappear', function() {

                $('#forgotPasswordForm').submit(function() {
                    var form = $('#forgotPasswordForm');
                    if(!form.valid()) return false;

                    var xhr = this.getRequest('customer_forgot_password');
                    if(!xhr) {
                        xhr = this.createRequest('customer_forgot_password', form.attr('action'));
                        xhr.setOnSuccess(function(datas) {
                            if(datas.success) {
                                page.goBack();
                                new Alert(datas.message_success, 'success').show();
                            }
                        });
                    }

                    xhr.setDatas(form.serializeArray()).send();

                    return false;
                }.bind(this));

            }).setCallback('willdisappear', function() {
                $('#forgotPasswordForm').unbind('submit');
            });
            subpage.submit = function() {
                $('#forgotPasswordForm').submit();
            }
        </script>
        <?php else : ?>
        <p><?php echo $this->_("Please log in with your mobile phone") ?></p>
        <?php endif ?>
    </div>
</div>