<?php $video = $this->getVideo(); ?>
<?php $videos = $video->getVideos(); ?>
<?php if(count($videos) > 0) : ?>

<?php foreach($videos as $key => $link) : ?>
<?php echo $this->getLayout()->addPartial('row', 'core_view_default', 'media/gallery/video/l1/view/list/li.phtml')->setCurrentOption($this->getCurrentOption())->setCurrentVideo($video)->setKey($key)->setLink($link)->toHtml() ?>
<?php endforeach ?>
<li id="load_more_<?php echo $video->getId(); ?>" class="load_more video_<?php echo $video->getValueId(); ?> video_<?php echo $video->getValueId(); ?>_<?php echo $video->getId(); ?> clear align-center ">
    <div class="padding">
        <button class="button" onclick="page.getSubpage('<?php echo $video->getValueId(); ?>').loadMore(<?php echo $video->getId(); ?>);"<?php if(count($videos) < Media_Model_Gallery_Video_Abstract::MAX_RESULTS) : ?> style="display:none;"<?php endif; ?>>
            <?php echo $this->_("More videos") ?>
        </button>
    </div>
</li>

<?php else : ?>
<li class="video_<?php echo $video->getValueId(); ?> video_<?php echo $video->getValueId(); ?>_<?php echo $video->getId(); ?>">
    <p><?php echo $this->_("No videos matching your selection") ?></p>
</li>
<?php endif; ?>
