<div class="has_header" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="page_title" message="message"></sb-header>

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

    <div class="padding list l1">
        <ul>
            <li ng-repeat="item in collection" ng-click="showItem(item)">
                <div>
                    <img width="37" height="37" class="logo left" ng-src="{{ item.icon_url }}" ng-if="item.icon_url" />

                    <p class="text">
                        <span class="name bold">{{ item.title }}.</span>
                        <span>{{ item.text }}</span>
                    </p>

                    <div class="clear"></div>
                </div>

                <div class="image right" ng-if="item.image_url">
                    <div>
                        <span class="block" style="background-image: url('{{ item.image_url }}');" ></span>
                    </div>
                </div>

                <div class="clear"></div>

                <div class="details" ng-if="item.meta">
                    <span class="area1 left" ng-if="item.meta.area1">
                        <img ng-src="{{ item.meta.area1.picto }}" alt="" width="13" height="10px" />
                        {{ item.meta.area1.text }}
                    </span>
                    <span class="area3 right" ng-if="item.meta.area3">
                        <img ng-src="{{ item.meta.area3.picto }}" alt="" style="vertical-align:bottom" width="13" />
                        {{ item.meta.area3.text }}
                    </span>
                    <span class="area2 right" ng-if="item.meta.area2">
                        <img ng-src="{{ item.meta.area2.picto }}" alt="" style="vertical-align:bottom" width="13" height="12px" />
                        {{ item.meta.area2.text }}
                    </span>

                    <div class="clear"></div>
                </div>
            </li>
        </ul>
    </div>
</div>
