<?php $application = $this->getApplication(); ?>
<?php $block_subheader = $application->getBlock('subheader'); ?>
<?php $block_button = $application->getBlock('button'); ?>

<div class="newswall has_header" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="'<?php echo $application->getName(); ?>'" message="message"></sb-header>

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

    <div class="content">
        <ul ng-class="{news: !style_background_image}" class="content_news" ng-show="news.id">
            <li class="title padding" ng-class="{subheader: !style_background_image}">
                <div class="logo left">
                    <img width="37" height="37" class="logo_src" src="<?php echo $application->getLogo() ?>" />
                </div>
                <p class="text">
                    <span class="name bold"><?php echo $application->getName(); ?></span>
                </p>
                <div class="clear"></div>
                <div class="metas">
                    <span class="comments_date left">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/pencil.png', true), $block_subheader->getColor()); ?>" alt="" style="vertical-align:bottom" width="13" height="10px"/>
                        {{ news.created_at }}
                    </span>
                    <span class="likes_count right">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/like.png', true), $block_subheader->getColor()); ?>" alt="<?php echo $this->_('Likes') ?>" style="vertical-align:bottom" width="13" height="12px" />
                        {{ news.number_of_likes }}
                    </span>
                    <span class="comments_count right">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/comment.png', true), $block_subheader->getColor()); ?>" alt="<?php echo $this->_('Coms') ?>" style="vertical-align:bottom" width="13" />
                        {{ answers.length }}
                    </span>
                    <div class="clear"></div>
                </div>
            </li>
            <li class="details padding">
                <div class="image" ng-if="news.image_url">
                    <img ng-src="{{ news.image_url }}" alt="<?php echo $application->getName() ?>" title="<?php echo $application->getName() ?>" width="100%" />
                </div>
                <p class="text">
                    {{ news.text }}
                </p>
                <div class="a-center add_comment">
                    <button type="button" class="button icon_left" ng-click="show_form = true;">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/comment.png', true), $block_button->getColor()); ?>" width="25" height="20" />
                        <?php echo $this->_('Comment'); ?>
                    </button>
                    <button type="button" class="button icon_left" ng-click="addLike();">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/like.png', true), $block_button->getColor()); ?>" width="25" height="20" />
                        <?php echo $this->_('Like'); ?>
                    </button>
                </div>
            </li>

            <li class="padding scale-fade" ng-show="show_form == true;">
                <div class="comment_content">
                    <form class="commentForm" ng-submit="addAnswer();">
                        <textarea rows="6" class="input_comment large border" name="text" value="" ng-model="new_answer" placeholder="<?php echo $this->_("Your comment") ?>"></textarea>
                        <input type="hidden" name="status_id" value="{{ news.id }}" />
                        <div class="button">
                            <button type="submit" class="button"><?php echo $this->_('Validate'); ?></button>
                            <button type="button" ng-click="show_form = false;" class="button reverse"><?php echo $this->_('Cancel'); ?></button>
                        </div>
                    </form>
                </div>
                <div class="clear"></div>
            </li>

            <li class="padding comments answer" ng-repeat="answer in answers">
                <div>
                    <img width="35" height="35" class="logo left" ng-src="{{ answer.customer_image_url }}" title="{{ answer.customer_name }}" alt="{{ answer.customer_name }}" />
                    <p class="text"><span class="customer_name bold">{{ answer.customer_name }}</span>{{ answer.text }}</p>
                    <div class="clear"></div>
                </div>
            </li>
            <li class="separator"></li>

        </ul>
    </div>

</div>