<?php $application = $this->getApplication(); ?>
<?php $isOverview = $this->getRequest()->getParam('overview', 0); ?>
<?php $time = time(); ?>
<?php echo $this->doctype() ?>
<html>
    <head>
        <title><?php echo $application->getName() ?></title>
        <?php foreach($this->getMetas() as $meta) : ?>
        <meta <?php echo $meta->getTag() ?>="<?php echo $meta->getKey(); ?>" content="<?php echo $this->_($meta->getContent()); ?>" />
        <?php endforeach ?>

        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <link href="<?php echo $application->getStartupImageUrl(); ?>?<?php echo $time; ?>" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 1)" rel="apple-touch-startup-image">
        <link href="<?php echo $application->getStartupImageUrl(); ?>?<?php echo $time; ?>" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
        <link href="<?php echo $application->getStartupImageUrl('retina4'); ?>?<?php echo $time; ?>" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">

        <link rel="icon" type="image/png" href="<?php echo $application->getIcon(32); ?>" />
        <link rel="shortcut icon" id="favicon" type="image/x-icon" href="<?php echo $application->getIcon(32); ?>" />

        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $application->getIcon(114) ?>" />
        <link rel="apple-touch-icon" href="<?php echo $application->getIcon(57) ?>" />

        <?php echo $this->getPartialHtml('style'); ?>
        <?php /* <link href="<?php echo $this->getUrl('front/mobile/style'); ?>" media="screen" rel="stylesheet" type="text/css"> */ ?>
        <?php echo $this->headLink() ?>

    </head>
    <body>
        <?php echo $this->getPartialHtml("body"); ?>
        <?php echo $this->headScript() ?>
        <script type="text/javascript">
            App.run(function($window, Customer) {
                Customer.id = <?php echo $this->getSession()->isLoggedIn() ? $this->getSession()->getCustomerId() : "null"; ?>;
                console.log("Is logged in : ", Customer.isLoggedIn());

                (function(d){
                    var js, id = 'facebook-jssdk';if (d.getElementById(id)) {return;}
                    js = d.createElement('script');js.id = id;js.async = true;
                    js.src = "//connect.facebook.net/en_US/sdk.js";
                    d.getElementsByTagName('head')[0].appendChild(js);
                }($window.document));

            }).config(function($facebookProvider) {
                $facebookProvider.setCustomInit({xfbml: false, version : 'v2.0'});
                $facebookProvider.setAppId("<?php echo $application->getFacebookId(); ?>");
                $facebookProvider.setPermissions("<?php echo Customer_Model_Customer_Type_Facebook::getScope() ?>");
            });
        </script>
    </body>
</html>
