<div sb-background-image value-id="'homepage'" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-connection has-connection="has_connection"></sb-connection>

    <div id="tabbar_items" class="tabbar_items type_scroll slide-top {{ layout_id }}" ng-show="tabbar_is_visible">
        <ul id="tabbar" class="tabbar_l5">
            <li>
                <?php /*option.is_visible && */ ?>
                <a ng-repeat="option in limited_options" ng-if="option.is_active" href="{{ option.url }}"  class="tabbar item" ng-class="{ is_link: option.is_link }">
                    <div>
                        <img ng-src="{{ option.icon_url }}" ng-class="{ colorable: option.icon_is_colorable }" width="70" height="70" />
                        <span class="tabbar no-background block">{{ option.name }}</span>
                    </div>
                </a>

                <a ng-if="customer_account.is_visible" href="{{ customer_account.url }}" class="tabbar item">
                    <div>
                        <img ng-src="{{ customer_account.icon_url }}" ng-class="{ colorable: customer_account.icon_is_colorable }" width="70" height="70" />
                        <span class="tabbar no-background block">{{ customer_account.name }}</span>
                    </div>
                </a>
            </li>
        </ul>
    </div>

</div>