<?php $application = $this->getApplication(); ?>
<?php $upload_path = Application_Model_Application::getImagePath().'/startup_image/'; ?>
<!--[if gte IE 10]><!-->
<div class="left">
    <button type="button" class="retina upload editor_menu active image_left">
        <i class="icon-camera-retro" style="margin-top:6px"></i>
        <?php echo $this->_('Choose a <br /><span class="bold">picture</span>'); ?><br />
    </button>
    <p class="recommended_size"><?php echo $this->_('Recommanded size:'); ?> 640x1096</p>
</div>
<div class="right" style="text-align:right">
    <button type="button" class="normal upload editor_menu active image_left">
        <i class="icon-camera-retro" style="margin-top:6px"></i>
        <?php echo $this->_('Choose a <br /><span class="bold">picture</span>'); ?><br />
    </button>
    <p class="recommended_size"><?php echo $this->_('Recommanded size:'); ?> 640x920</p>
</div>
<!--<![endif]-->
<div id="fileupload_old_broswer" style="display:none">
    <p class="left">
        <?php echo $this->_('Choose a <br /><span class="bold">picture</span>'); ?><br />
        <span class="recommended_size">(640*1096)</span>
    </p>
    <p class="right">
        <?php echo $this->_('Choose a <br /><span class="bold">picture</span>'); ?><br />
        <span class="recommended_size">(640*920)</span>
    </p>
    <div class="clear"></div>
</div>
<input class="fileupload retina" type="file" style="display:none" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
<input class="fileupload normal" type="file" style="display:none" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
<div class="clear"></div>
<div id="capture_conteneurs">
    <div class="left" id="crop_startupimage_cont_retina"></div>
    <div class="right" id="crop_startupimage_cont"></div>
    <div class="clear"></div>
</div>
<script type="text/javascript">
    var startup_uploader = new Uploader();
    $(document).ready(function() {

        if(!$('button.upload').is(':visible')) {
            $('input.fileupload').show();
            $('#fileupload_old_broswer').show()
        }

        $('#startup_conteneur').find('.upload').click(function(){
            if($(this).hasClass('normal')) {
                $('input.normal').trigger('click');
            } else {
                $('input.retina').trigger('click');
            }
            return false;
        });

        $('#startup_conteneur').find('.fileupload').fileupload({
            dataType: 'json',
            add: function (e, data) {
                if($(this).hasClass('normal')) {
                    var type = 'normal';
                } else {
                    var type = 'retina';
                }
                data.formData = {
                    fileType: type,
                    uniq_prefix: type+'_',
                    minwidth: '100',
                    minheight: '200',
                    maxwidth: '2000',
                    maxheight: '2000'
                },
                data.submit();
                startup_uploader.showProgressbar();
            },
            progressall: function (e, data) {
                startup_uploader.moveProgressbar(data);
            },
            done: function (e, data) {
                if(data.result.error) {
                    startup_uploader.showError(data.result.message);
                } else {
                    var suffix = $(this).hasClass('retina') ? '_retina' : '';
                    startup_uploader.hide();
                    var params = new Array();
                    params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                    params["file"] = data.result.files;
                    if($(this).hasClass('normal')) {
                        params["output_w"] = 640;
                        params["output_h"] = 920;
                        params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('application/customization_publication_app/savestartup')) ?>$filetype$normal';
                    } else {
                        params["output_w"] = 640;
                        params["output_h"] = 1096;
                        params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('application/customization_publication_app/savestartup')) ?>$filetype$retina';
                    }
                    params["uploader"] = 'startup_uploader';
                    startup_uploader.crop(params);
                    startup_uploader.callback = function(file) {
                        $('#startupimage'+suffix).removeAttr('style').hide().attr('src', '<?php echo $upload_path ?>'+file).attr('data-image', '<?php echo $upload_path ?>'+file).fadeIn();
                        if(suffix == '_retina') {
                            $('#crop_startupimage_cont_retina').html('<img src="<?php echo $upload_path ?>'+file+'" width="160px" height="274px"/>');
                        } else {
                            $('#crop_startupimage_cont').html('<img src="<?php echo $upload_path ?>'+file+'" width="160px" height="230px"/>');
                        }
                    }
                }
            }
        });

    });

</script>

<style>
    #browse_panel h3.title {
        font-size: 18px;
        font-weight: normal;
        margin-bottom: 10px;
    }
    .upload {
        margin-top:20px;
    }
    div.crop_controls_retina, div.crop_controls {
        margin-top: 20px;
        width: 200px;
    }
    .bar {
        height: 18px;
        background: green;
    }
</style>