<?php $video = $this->getCurrentVideo(); ?>
<?php $option_value = $this->getCurrentOptionValue(); ?>
<?php $key = $this->getCurrentKey(); ?>
<?php $picto = $video->getTypeId() == 'itunes' ? 'podcast' : $video->getTypeId(); ?>
<tr id="row_<?php echo $video->getId(); ?>" class="row_video">
    <td><img class="youtube" src="<?php echo $this->getImage("pictos/$picto.png"); ?>" title="<?php echo ucfirst($picto); ?>" alt="<?php echo ucfirst($picto); ?>" width="43" height="43" data-color="color" data-style="area" /></td>
    <td><input type="text" name="name" value="<?php echo $video->getName(); ?>" placeholder="<?php echo $this->_('Gallery Name') ?>" class="required input" /></td>
    <td <?php if($video->getTypeId()=='itunes'):?>colspan="2"<?php endif;?>>
        <input type="text" name="param" value="<?php echo $video->getParam(); ?>" placeholder="<?php echo $this->_('Parameter/Feed Url') ?>" class="required input <?php if($video->getTypeId()=='itunes'):?>full_td<?php endif;?>" />
    </td>
    <?php if($video->getType()):?>
        <td>
            <select name="type" class="youtube_type required" id="video_type_<?php echo $video->getId() ?>" tabindex="<?php echo $key; ?>" tabindex="<?php echo $key ?>">
                <option value=""><?php echo $this->_('Type') ?></option>
                <?php foreach($video->getAllTypes() as $type) : ?>
                    <option value="<?php echo $type ?>"<?php if($video->getType() == $type) :?> selected="selected"<?php endif; ?>><?php echo ucfirst($type); ?></option>
                <?php endforeach; ?>
            </select>
        </td>
    <?php endif;?>
    <td>
        <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
        <?php if($video->getId() != 'new') : ?>
            <input type="hidden" name="id" value="<?php echo $video->getId(); ?>" />
        <?php endif; ?>
        <button type="button" class="default_button save_video left"><?php echo $this->_('OK'); ?></button>
    </td>
    <td><button type="button" class="delete delete_video" rel="<?php echo $video->getId(); ?>"><i class="icon-remove"></i></button></td>
</tr>