<?php $option_value = $this->getCurrentOptionValue(); ?>
<?php $image = $this->getCurrentImage(); ?>

<tr class="row_image" rel="<?php echo $image->getId(); ?>">
    <td>
        <?php if($image->getTypeId() == 'instagram') : ?>
        <img src="<?php echo $this->getImage('customization/pictos/instagram.png'); ?>" title="Instagram" alt="I" width="28" />
        <?php elseif($image->getTypeId() == 'picasa') : ?>
        <img src="<?php echo $this->getImage('customization/pictos/picasa.png'); ?>" title="Picasa" alt="Picasa" width="28" />
        <?php elseif($image->getTypeId() == 'custom') : ?>
        <img src="<?php echo $this->getImage('customization/pictos/camera.png'); ?>" title="Utilisateur" alt="<?php echo $this->_('User') ?>" width="28" />
        <?php endif; ?>
    </td>
    <td><input type="text" name="name" value="<?php echo $image->getName(); ?>" placeholder="<?php echo $this->_('Gallery Name') ?>" class="input required" /></td>
    <td>
    <?php if($image->getTypeId() == 'custom') : ?>
        <?php $gallery = new Media_Model_Gallery_Image_Custom(); ?>
        <?php $gs = $gallery->findAll(array('gallery_id' => $image->getId())); ?>
        <button type="button" id="input_<?php echo $image->getId(); ?>" class="search_input upload_picture default_button btn-block" rel="list_<?php echo $image->getId(); ?>">
            <?php if($gs->count() == 0) : ?>
            <?php echo $this->_('Send your pictures') ?>
            <?php else : ?>
            <?php echo $this->_('Picture%s', $gs->count() <= 1 ? '' : 's') ?>
            <?php endif; ?>
        </button>
        <?php foreach($gs as $p) : ?>
        <input type="hidden" id="image_<?php echo $image->getId(); ?>_<?php echo $p->getId(); ?>_title_receiver" name="images[list_<?php echo $image->getId(); ?>][<?php echo $p->getId(); ?>][title]" value="<?php echo $p->getTitle(); ?>" />
        <input type="hidden" id="image_<?php echo $image->getId(); ?>_<?php echo $p->getId(); ?>_description_receiver" name="images[list_<?php echo $image->getId(); ?>][<?php echo $p->getId(); ?>][description]" value="<?php echo $p->getDescription(); ?>" />
        <input type="hidden" name="images[list_<?php echo $image->getId(); ?>][<?php echo $p->getId(); ?>][image_id]" value="<?php echo $p->getId(); ?>" />
        <?php endforeach; ?>
    <?php else : ?>
        <input type="text" name="<?=($image->getTypeId() == 'instagram') ? 'param_instagram' : 'param'; ?>" class="search_input input required" value="<?=($image->getTypeId() == 'instagram') ? $image->getParamInstagram() : $image->getParam(); ?>" placeholder="<?php echo $this->_('Parameter') ?>" />
    <?php endif; ?>
    </td>
    <td>
        <button type="button" class="validate default_button save_image" rel="<?php echo $image->getId(); ?>">OK</button>
    </td>
    <td>
        <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
        <input type="hidden" name="id" value="<?php echo $image->getId(); ?>" />
        <button type="button" class="delete red default_button delete_image"><i class="icon-remove"></i></button>
    </td>
</tr>