<?php $application = $this->getApplication(); ?>
<?php $upload_path = Application_Model_Application::getImagePath().'/homepage_image/'; ?>
<!--[if gte IE 10]><!-->
<div class="left">
    <button type="button" class="bg upload editor_menu active">
        <i class="icon-camera-retro"></i>
        <?php echo $this->_('Change your'); ?><br/>
        <span class="bold"><?php echo $this->_('picture'); ?></span><br/>
    </button>
    <p class="recommended_size"><?php echo $this->_('Recommanded size:'); ?> 640x1096</p>
</div>
<div class="right">
    <button type="button" class="bg_lowres upload editor_menu active right">
        <i class="icon-camera-retro"></i>
        <?php echo $this->_('Change your'); ?><br/>
        <span class="bold"><?php echo $this->_('picture'); ?></span><br/>
    </button>
    <div class="clear"></div>
    <p class="clear recommended_size"><?php echo $this->_('Recommanded size:'); ?> 640x920</p>
</div>
<!--<![endif]-->
<div id="fileupload_old_browser" style="display:none">
    <p class="left">
        <?php echo $this->_('Change your'); ?> <span class="bold"><?php echo $this->_('picture'); ?></span> <span class="recommended_size">(640*1096)</span>
    </p>
    <p class="right">
        <?php echo $this->_('Change your'); ?> <span class="bold"><?php echo $this->_('picture'); ?></span> <span class="recommended_size">(640*920)</span>
    </p>
    <div class="clear"></div>
</div>
<input enctype="multipart/form-data" class="fileupload bg left" type="file" style="display:none" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
<input enctype="multipart/form-data" class="fileupload bg_lowres right" type="file" style="display:none" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
<div class="clear"></div>
<div id="use_homepage_background_area">
   <label id="use_homepage_background_image_label" class="checkbox" for="use_homepage_background_image">
        <input type="checkbox" <?php if($application->getUseHomepageBackgroundImageInSubpages() == 1) : ?>checked="checked"<?php endif; ?> id="use_homepage_background_image" name="use_homepage_background_image_in_subpages" value="1" />
        <?php echo $this->_("Use into all of your application\'s pages"); ?>
    </label>
    <img width="24" style="display:none;" title="Loading" alt="Loading" id="loader_use_homepage_background_image" src="<?php echo $this->getImage('customization/ajax/spinner.gif') ?>">
</div>
<div id="capture_conteneurs">
    <div class="left" id="crop_image_bg_cont"></div>
    <div class="right" id="crop_image_lowres_cont"></div>
    <div class="clear"></div>
</div>
<script type="text/javascript">
        if(!$('button.bg_lowres').is(':visible')) {
            $('input.fileupload').show();
            $('#fileupload_old_browser').show()
        }

        var homepage_uploader = new Uploader();
        var type = '';
        $('.fileupload').fileupload({
            autoUpload: true,
            dataType: 'json',
            type: 'POST',
            add: function (e, data) {
                if($(this).hasClass('bg_lowres')) {
                    type = 'bg_lowres';
                } else {
                    type = 'bg';
                }
                data.formData = {
                    fileType: type,
                    uniq_prefix: type+'_',
                    minwidth: '100',
                    minheight: '200',
                    maxwidth: '2000',
                    maxheight: '2000'
                },
                data.submit();
                homepage_uploader.showProgressbar();
            },
            progressall: function (e, data) {
                homepage_uploader.moveProgressbar(data);
            },
            done: function (e, data) {
                if(data.result.error) {
                    homepage_uploader.showError(data.result.message);
                } else {
                    homepage_uploader.hide();
                    var params = new Array();
                    params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                    params["file"] = data.result.files;
                    params["uploader"] = 'homepage_uploader';
                    if($(this).hasClass('bg')) {
                        params["output_w"] = 640;
                        params["output_h"] = 1096;
                        params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('application/customization_design_style/savehomepage')) ?>$filetype$bg';
                    } else {
                        params["output_w"] = 640;
                        params["output_h"] = 920;
                        params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('application/customization_design_style/savehomepage')) ?>$filetype$bg_lowres';
                    }
                    homepage_uploader.crop(params);
                    homepage_uploader.callback = function(file) {
                        if(type == 'bg') {
                            iframe.f.homepage_retina4 = '<?php echo $upload_path ?>bg/'+file;
                            $('#homepage_retina_cont #homepage_retina').attr('src', '<?php echo $upload_path ?>bg/'+file).removeAttr('style');
                            $('#crop_image_bg_cont').html('<img src="<?php echo $upload_path ?>bg/'+file+'" width="160px" height="274px"/>')
                        } else {
                            iframe.f.homepage_normal = '<?php echo $upload_path ?>bg_lowres/'+file;
                            $('#homepage_cont #homepage_standard').attr('src', '<?php echo $upload_path ?>bg_lowres/'+file).removeAttr('style');
                            $('#crop_image_lowres_cont').html('<img src="<?php echo $upload_path ?>bg_lowres/'+file+'" width="160px" height="230px"/>')
                        }
                        iframe.f.page.setBackgroundHomePage();
                    }
                }
            }
        });

        $('.upload').click(function(){
            if($(this).hasClass('bg_lowres')) {
                $('input.bg_lowres').trigger('click');
            } else {
                $('input.bg').trigger('click');
            }
            return false;
        });

        $('#use_homepage_background_image').change(function() {
            var bg_loader = $('#loader_use_homepage_background_image').show();
            reload(this.parentNode, '<?php echo $this->getUrl('application/customization_design_style/mutualizebackgroundimages'); ?>', true, function(datas) {
                bg_loader.hide();
            }, function() {
                bg_loader.hide();
            });
        });

</script>

<style>
    #browse_panel h3.title {
        font-size: 18px;
        font-weight: normal;
        margin-bottom: 10px;
    }
    .upload {
        margin-top:20px;
    }
    div.crop_controls_bg {
        margin-bottom: 20px;
    }
    div.crop_controls_bg, div.crop_controls_lowres {
        margin-top: 20px;
    }
    .bar {
        height: 18px;
        background: green;
    }
    #crop_image_bg_cont img, #crop_image_lowres_cont img {
        border: solid 1px white;
    }
    div#use_homepage_background_area {
        margin-top: 20px;
    }
    div#capture_conteneurs {
        margin-top: 20px;
    }
</style>