<?php $application = $this->getApplication(); ?>
<?php $option = $this->getOptionValue(); ?>
<?php $message = new Push_Model_Message(); ?>
<?php $messages = $message->findAll(null, 'created_at DESC'); ?>
<?php $canSendMessages = Push_Model_Certificat::getAndroidKey() && Push_Model_Certificat::getiOSCertificat() ?>
<div class="edit_page push_notif">
    <div id="list" class="">
        <div class="section">
            <h4 class="subtitle">
                <span class="left area"><?php echo $this->_('Add'); ?></span>
                <hr class="area reverse">
                <?php if($canSendMessages) : ?>
                <span class="area right">
                    <button type="button" onclick="feature.edit();" class="default_button add right" id="add_item">
                        <i class="icon-plus"></i>
                    </button>
                </span>
                <?php endif; ?>
                <div class="clear"></div>
            </h4>
            <?php if($canSendMessages) : ?>
            <?php echo $this->createPartialHtml('no_item', 'core_view_default', 'application/customization/features/edit/no_item.phtml'); ?>
            <?php else : ?>
            <p><?php echo $this->_('<a href="%s">Click here to provide the required information to send push notifications</a>', $this->getUrl('push/certificat/list')); ?></p>
            <?php endif; ?>
        </div>
        <?php if($messages->count()) : ?>
        <div class="section">
            <h4 class="subtitle">
                <span class="left area"><?php echo $this->_('Manage'); ?></span>
                <hr class="area reverse">
                <span class="area right">
                    <button type="button" class="default_button" id="toggle_existing_items">
                        <i class="icon-chevron-down"></i>
                    </button>
                </span>
                <div class="clear"></div>
            </h4>
            <div id="existing_items">
                <ul class="list">
                    <?php foreach($messages as $message) : ?>
                    <?php $text = trim($message->getText()); ?>
                    <?php if(empty($text)) continue; ?>
                    <li id="push_actions_<?php echo $message->getId(); ?>" class="push_actions" rel="<?php echo $message->getId(); ?>">
                        <p class="title left"><?php echo $message->getTitle() ?></p>
                        <div class="icons right" id="icons_<?php echo $message->getId(); ?>">
                            <a href="javascript:void(0)" class="icon more" onclick="var div = $('#details_<?php echo $message->getId(); ?>'); if(div.is(':visible')) {div.slideUp(300, function() {$(this).parent('li').removeClass('selected bg-blue2')});} else {div.slideDown().parent('li').addClass('selected');} return false;">
                                <i class="icon-search"></i>
                            </a>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                        <div id="details_<?php echo $message->getId(); ?>" class="details" style="display: none;">
                            <table class="list list-label">
                                <tr class="first">
                                    <td class="label"><?php echo $this->_('Message'); ?> :</td>
                                    <td><span class="bold"><?php echo $message->getText() ?></span></td>
                                </tr>
                                <tr class="first">
                                    <td class="label"><?php echo $this->_('Creation date'); ?> :</td>
                                    <td><span class="bold"><?php echo $message->getFormattedCreatedAt() ?></span></td>
                                </tr>
                                <tr class="first">
                                    <td class="label"><?php echo $this->_("Sending date"); ?> :</td>
                                    <td><span class="bold"><?php echo $message->getStatus() == 'delivered' ? $message->getFormattedDeliveredAt() : $this->_('Pending'); ?></span></td>
                                </tr>
                            </table>
                        </div>
                    </li>
                    <li class="separator area reverse"></li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
        <?php endif; ?>

        <div class="section">
            <?php
                echo $this->getLayout()
                    ->addPartial('background_image', 'Core_View_Default', 'application/customization/features/edit/background_image.phtml')
                    ->setValueId($option->getId())
                    ->toHtml()
                ;
            ?>
        </div>

    </div>

    <div id="edit" class="" style="display: none;">
        <div id="push_step_one" class="section push_step" pos="1">
            <h4 class="subtitle">
                <span class="left area"><?php echo $this->_('Editing'); ?></span>
                <hr class="area reverse">
                <div class="clear"></div>
            </h4>
            <div class="block">
                <form id="pushFirstStepForm" method="post">
                    <div class="buttons">
                        <button type="button" onclick="feature.list()" class="delete left"><i class="icon-arrow-left"></i></button>
                        <button type="submit" class="default_button right"><i class="icon-arrow-right"></i></button>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                    <?php /*if($current_pos->getId()) : ?>
                    <input type="hidden" name="outlets[]" value="<?php echo $current_pos->getId(); ?>" />
                    <input type="hidden" name="pos_id" value="<?php echo $current_pos->getId(); ?>" />
                    <?php endif;*/ ?>
                    <table class="list list-input" width="450px">
                        <col width="50%" />
                        <col width="50%" />
                        <tr>
                            <td class="label"><label for="title"><?php echo $this->_('Title:'); ?> <span class="input-required">*</span></label></td>
                            <td><input type="text" id="push_title" name="title" class="required input" value="" /></td>
                        </tr>
                        <tr>
                            <td class="label"><label for="text"><?php echo $this->_('Message:'); ?> <span class="input-required">*</span></label></td>
                            <td><input type="text" id="push_text" name="text" class="required input" value="" /></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <div id="push_step_two" class="section push_step" style="display:none;" pos="2">
            <h4 class="subtitle">
                <span class="left area"><?php echo $this->_('Locate'); ?></span>
                <hr class="area reverse">
                <div class="clear"></div>
            </h4>
            <div id="push_gmaps">
                <form id="pushSecondStepForm" method="post">
                    <div class="buttons">
                        <button type="button" onclick="push.goToStep('one');" class="delete left"><i class="icon-arrow-left"></i></button>
                        <button type="submit" class="default_button right"><i class="icon-arrow-right"></i></button>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <div class="use_gmaps">
                            <div>
                                <label for="use_gmaps_0" class="radio" onclick="gmaps.hide(); gmaps.deactivateFields();">
                                    <input type="radio" id="use_gmaps_0" name="use_gmaps" class="use_gmaps" value="0" checked="checked" />
                                    <?php echo $this->_("Send to all my users"); ?>
                                </label>
                            </div>
                            <div>
                                <label for="use_gmaps_1" class="radio" onclick="gmaps.init().show();">
                                    <input type="radio" id="use_gmaps_1" name="use_gmaps" class="use_gmaps" value="1" />
                                    <?php echo $this->_("Send to a specific location"); ?>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div id="gmaps_datas" class="none">
                        <?php //<div class="relative"> ?>
                            <table class="no-collapse" width="600px" cellspacing="15">
                                <col width="50%" />
                                <col width="50%" />
                                <tr>
                                    <td class="label"><label for="title"><?php echo $this->_('Enter a location:'); ?> <span class="input-required">*</span></label></td>
                                    <td class="label"><label for="title"><?php echo $this->_('And a radius (in Km):'); ?> <span class="input-required">*</span></label></td>
                                </tr>
                                <tr>
                                    <td><input type="text" class="gmaps_field required" id="push_target" disabled="disabled" /></td>
                                    <td><input type="text" class="gmaps_field required" id="push_radius" disabled="disabled" placeholder="<?php echo $this->_('Radius'); ?>" /></td>
                                </tr>
                            </table>
                            <div class="relative">
                                <div id="push_map_canvas_receiver">
                                </div>
                                <?php /*<div id="mask_gmaps" class="overlay"></div>*/ ?>
                            </div>
                    </div>
                </form>
            </div>
        </div>

        <div id="push_step_three" class="section push_step" style="display:none;" pos="3">
            <h4 class="subtitle">
                <span class="left area"><?php echo $this->_('Additionnal Information'); ?></span>
                <hr class="area reverse">
                <div class="clear"></div>
            </h4>
            <div id="">
                <form id="pushThirdStepForm" action="<?php echo $this->getUrl('push/application/editpost') ?>" method="post">

                    <div class="buttons">
                        <button type="button" onclick="push.goToStep('two');" class="delete left"><i class="icon-arrow-left"></i></button>
                        <button type="submit" class="default_button right"><?php echo $this->_('OK'); ?></button>
                        <div class="clear"></div>
                    </div>
                    <div>

                        <div class="details">
                            <div class="relative">
                                <span class="block left"><?php echo $this->_("I want to send it"); ?></span>
                                <ul class="left">
                                    <li>
                                        <label for="send_now" class="radio" onclick="$('#push_datepicker_send_at').fadeOut(150).attr('disabled', 'disabled');">
                                            <input type="radio" id="send_now" name="send_at_a_specific_datetime" value="0" checked="checked" />
                                            <?php echo $this->_("now"); ?>
                                        </label>
                                    </li>
                                    <li>
                                        <label for="send_at_a_specific_datetime" class="radio" onclick="$('#push_datepicker_send_at').removeAttr('disabled').fadeIn(150, function() {$('#push_datepicker_send_at').focus();});">
                                            <input type="radio" id="send_at_a_specific_datetime" name="send_at_a_specific_datetime" value="1" />
                                            <?php echo $this->_("on a specific date"); ?>
                                        </label>
                                    </li>
                                </ul>
                                <div class="left">
                                    <input type="text" id="push_datepicker_send_at" class="push_datetimepicker required" name="send_at" value="" style="display:none;" />
                                </div>
                                <div class="clear"><br /></div>
                            </div>

                            <div class="relative is_geolocated">
                                <span class="block left"><?php echo $this->_("and users entering the area"); ?></span>
                                <ul class="left">
                                    <li>
                                        <label for="send_just_now" class="radio" onclick="$('#push_datepicker_send_until').fadeOut(150).attr('disabled', 'disabled');">
                                            <input type="radio" id="send_just_now" name="send_until_a_specific_datetime" value="0" checked="checked" />
                                            <?php echo $this->_("now"); ?>
                                        </label>
                                    </li>
                                    <li>
                                        <label for="send_until_a_specific_datetime" class="radio" onclick="$('#push_datepicker_send_until').removeAttr('disabled').fadeIn(150, function() {$('#push_datepicker_send_until').focus();});">
                                            <input type="radio" id="send_until_a_specific_datetime" name="send_until_a_specific_datetime" value="1" />
                                            <?php echo $this->_("for a limited period"); ?>
                                        </label>
                                    </li>
                                </ul>
                                <div class="left">
                                    <input type="text" id="push_datepicker_send_until" class="push_datetimepicker required" name="send_until" value="" style="display:none;" />
                                </div>
                                <div class="clear"></div>
                            </div>

<!--                            <select id="sent_until" class="is_geolocated push_select left" tabindex="2">
                                <option>sans limite</option>
                                <option>jusqu'au </option>
                            </select>-->
                        </div>
                    </div>

                    <input type="hidden" name="option_value_id" value="<?php echo $option->getId(); ?>" />
                    <input type="hidden" id="push_title_receiver" name="title" value="" />
                    <input type="hidden" id="push_text_receiver" name="text" value="" />
                    <input type="hidden" id="push_latitude_receiver" name="latitude" class="gmaps_field" value="" disabled="disabled" />
                    <input type="hidden" id="push_longitude_receiver" name="longitude" class="gmaps_field" value="" disabled="disabled" />
                    <input type="hidden" id="push_radius_receiver" name="radius" class="gmaps_field" value="" disabled="disabled" />
                </form>
            </div>
        </div>

<!--        <form id="messageCreateForm" action="<?php echo $this->getUrl('push/application/editpost') ?>" method="post">
            <input type="hidden" name="option_value_id" value="<?php echo $option->getId(); ?>" />
            <input type="hidden" id="push_latitude_receiver" name="latitude" class="gmaps_field" value="" disabled="disabled" />
            <input type="hidden" id="push_longitude_receiver" name="longitude" class="gmaps_field" value="" disabled="disabled" />
            <input type="hidden" id="push_radius_receiver" name="radius" class="gmaps_field" value="" disabled="disabled" />
        </form>-->
    </div>
    <script type="text/javascript">

        page.setCallback('didappear', function() {

            push.init();
            $('#toggle_existing_items').click(function() {
                $('#existing_items').stop().slideToggle(300, function() {
                    if($(this).is(':visible')) $('#toggle_existing_items').children('i').removeClass('icon-chevron-down').addClass('icon-chevron-up');
                    else $('#toggle_existing_items').children('i').removeClass('icon-chevron-up').addClass('icon-chevron-down');
                });
            });

            if(!$('#gmaps_libraries').length) {
                var script_tag = document.createElement('script');
                script_tag.setAttribute("id","gmaps_libraries");
                script_tag.setAttribute("type","text/javascript");
                script_tag.setAttribute("src","http://maps.google.com/maps/api/js?sensor=false&libraries=places&callback=initializeGmaps");
                (document.getElementsByTagName("head")[0] || document.documentElement).appendChild(script_tag);
            }
        });

        page.setCallback('willdisappear', function() {
            gmaps.destroy();
            push.destroy();
            $('#toggle_existing_items').unbind('click');
        });

        // Callback Gmaps
        function initializeGmaps() {

        }

        var push = {
            init: function() {

                createCustomUI();
                $('.push_datetimepicker').datetimepicker({
                    dateFormat: 'yy-mm-dd'
                });

                $('.push_select').each(function() {
                    $(this).dropkick();
                });

                $('#pushFirstStepForm').submit(function(e) {
                    if($(e.currentTarget).valid()) {
                        $('#push_title_receiver').val($('#push_title').val());
                        $('#push_text_receiver').val($('#push_text').val());
                        this.goToStep('two');
                    }
                    return false;
                }.bind(this));
                $('#pushSecondStepForm').submit(function(e) {
                    if($(e.currentTarget).valid()) {
                        this.goToStep('three');
                    }
                    return false;
                }.bind(this));

                $('#pushThirdStepForm').submit(function() {

                    if(!$(this).valid()) return false;
                    reload(this, this.action, true, function(datas) {
                        if(datas.success) {
                            page.reload();
                        }
                    });

                    return false;
                });
            },
            goToStep: function(step) {

                gmaps.hide();
                var newDiv = $('#push_step_'+step);
                var appearCallback = function() {$('#page').removeAttr('style'); newDiv.removeAttr('style');}

                if(step == 'two') {
                    appearCallback = function() {
                        if($('#use_gmaps_1').is(':checked')) {
                            gmaps.show();
                        }
                        $('#page').removeAttr('style');
                        newDiv.removeAttr('style');
                    }
                }

                animation.slide($('.push_step:visible'), newDiv, function() {}, function() {});
                $('#page').animate({height: $('#icon_and_name').outerHeight(true) + newDiv.outerHeight(true)}, 500, null, appearCallback);

            },
            destroy: function() {
                $('.push_datetimepicker').datepicker("destroy");
                $('#pushFirstStepForm').unbind('submit');
                $('#pushSecondStepForm').unbind('submit');
                $('#pushThirdStepForm').unbind('submit');
                $('#messageCreateForm').unbind('submit');
                $('.use_gmaps').unbind('change');
            }
        }

    </script>
    <style>
        .push_notif form { margin: 0; }
        .push_notif .push_step { width: 100%; }
        .push_notif h4.subtitle span.area.can_send_notif { width: 320px; }
        .push_notif h4.subtitle span.area.can_send_notif div.span4 { width: 270px; margin-left: 0; margin-right: 15px; }
        #filters table input { min-width: 160px }

        .push_notif label.toggleGmaps { line-height: 30px; font-size: 20px; }
        .push_notif #push_target { width: 300px; }
        .push_notif #push_radius { width: 60px; }
        .push_notif .is_geolocated { display: none; }
        .push_notif #mask_gmaps {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100%;
            border-radius: 5px;
            background-color: black;
            opacity: 0.5;
        }

        .push_notif #push_step_three div.details span.block.left {
            height: 65px;
            line-height: 65px;
            margin-right: 5px;
        }

        .push_notif .push_datetimepicker {
            margin-top: 8px;
            margin-left: 10px;
        }
        ul.list li {
            padding-top: 10px;
            padding-bottom: 10px;
        }
        div#list a.icon {
            margin-top: 0 !important;
        }
        .push_actions .title {
            width: 90% !important;
        }
    </style>
</div>