<?php $application = $this->getApplication(); ?>
<div class="previewer">
    <div class="first">
        <p class="blue10 f-bold"><?php echo $this->_('1. Download the app previewer:'); ?></p>
        <div class="left">
            <p><?php echo $this->_('Scan this QR Code:'); ?></p>
            <p><img src="<?php echo $this->getImage('previewer/qrcode.jpg'); ?>" title="<?php echo $this->_('Scan this QR Code'); ?>" alt="<?php echo $this->_("The QR Code is not available at this moment"); ?>" /></p>
            <p><?php echo $this->_('Or go on your store<br />and look for "Siberian CMS Previewer"'); ?></p>
        </div>
        <div class="right">
            <img src="<?php echo $this->getImage('previewer/presentation.jpg'); ?>" title="<?php echo $this->_('Télécharger notre application de prévisualisation'); ?>" alt="<?php echo $this->_('Télécharger notre application de prévisualisation'); ?>" />
        </div>
       <div class="clear"></div>
    </div>
    <div class="second">
        <p class="blue10 f-bold"><?php echo $this->_("2. Open the app and login"); ?></p>
    </div>
    <style>
        #modal_content_app_previewer p {
            font-size: 19px;
        }
        #modal_content_app_previewer .first div.left {
            padding-top:25px
        }

    </style>
</div>
