<?php $application = $this->getApplication(); ?>
<?php $is_overview = $this->getRequest()->getParam('overview'); ?>
<?php $option_values = $application->getPages($is_overview ? 10 : null); ?>
<?php $color = $this->getBlock('tabbar')->getImageColor(); ?>
<div class="general relative">
    <div id="homepage_content" class="content">
        <img id="homepage_background_image_link" src="" alt=""/>
    </div>
    <?php if($option_values->count() >= 9) : ?>
    <?php echo $this->getLayout()->addPartial('list_tabbar_items', 'core_view_mobile_default', 'html/l1/tabbar.phtml')->setOptionValues($option_values)->toHtml(); ?>
    <?php endif; ?>
</div>
<footer id="tabbar_items" class="tabbar_items tabbar l2 animated toBottom">
    <ul id="tabbar" class="tabbar_l2">
        <?php foreach($option_values as $k => $option_value) : ?>
        <?php if(!$option_value->isActive()) continue; ?>
        <li>
            <a href="<?php echo $option_value->getUrl('view', array('option_value_id' => $option_value->getId()), false); ?>" id="tabbar_item_<?php echo $option_value->getId(); ?>" rel="<?php echo $option_value->getId(); ?>" class="item item_<?php echo $option_value->getCode(); ?><?php if($option_value->getIsAjax()) : ?> is_ajax<?php endif; ?> not-loaded"<?php if(!$option_value->getIsDummy()) : ?> onclick="page.showSubpage({a:this}); return false;"<?php endif; ?><?php if($option_value->isLink()) : ?> attr-link="is_link"<?php endif; ?>>
                <img id="icon_<?php echo $option_value->getId(); ?>" src="<?php echo $this->getColorizedImage($option_value->getIconId(), $color); ?>" class="<?php echo $option_value->getImage()->getCanBeColorized() ? 'colorable' : '' ?>" alt="" title="" width="30" height="30" />
                <span id="tabbar_name_<?php echo $option_value->getId(); ?>" class="tabbar_name_<?php echo $option_value->getId(); ?> block"><?php echo $option_value->getShortTabbarName(); ?></span>
            </a>
        </li>
        <?php endforeach; ?>
        <?php if($application->usesUserAccount()) : ?>
        <?php $option_value = new Application_Model_Option_Value(); ?>
        <?php $option_value->findTabbarAccount(); ?>
        <li>
            <a href="javascript:void(0)" id="tabbar_item_customer_account" class="item" onclick="customer.openLoginForm();" rel="customer_account">
                <img src="<?php echo $this->getColorizedImage($option_value->getBaseIconUrl(), $application->getBlock('tabbar')->getImageColor()); ?>" class="colorable" alt="" title="" width="30" height="30" />
                <span id="tabbar_name_customer_account" class="tabbar_name_customer_account block"><?php echo $application->getShortTabbarAccountName() ?></span>
            </a>
        </li>
        <?php endif; ?>
        <?php $option_value = new Application_Model_Option_Value(); ?>
        <?php $option_value->findTabbarMore(); ?>
        <li id="more_items" style="display:none;">
            <a href="javascript:void(0)" id="tabbar_item_more_items" class="item" onclick="javascript:tabbar.showAllItems(); return false;" rel="more_items">
                <img id="icon_more" src="<?php echo $this->getColorizedImage($option_value->getBaseIconUrl(), $application->getBlock('tabbar')->getImageColor()); ?>" class="colorable" alt="" title="" width="30" height="30" />
                <span id="tabbar_name_more_items" class="tabbar_name_more_items block"><?php echo $application->getShortTabbarMoreName() ?></span>
            </a>
        </li>
    </ul>
    <script type="text/javascript">
        tabbar.nbr_of_icons_per_row = 5;
        tabbar.nbr_of_icons = 10;
        tabbar.setType('tabbar');

        //A ouvrir dans la webview
        if(typeof Android != "undefined") {
            $('#tabbar').find('a.item[attr-link]').each(function() {
                var href = $(this).attr('href');
                href += /\?/.test(this.search) ? "&webview=1" : "?webivew=1";
                $(this).attr('href', href);
            });
        }
    </script>
</footer>