<div class="has_header sidebar l1" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="page_title" message="message" right-button="header_right_button"></sb-header>

    <div class="subheader sidebar right slide-right" ng-hide="!show_sidebar">
        <div class="content">
            <ul ng-click="show_sidebar = false;">
                <li ng-repeat="item in collection">
                    <a class="item reverse" ng-click="showItem(item);" ng-class="{subheader: current_item == item}">
                        {{ item.name }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="subheader content">
        <div>
            <h3 class="title" ng-show="current_item.name">{{ current_item.name }}</h3>
            <p class="small loader" ng-hide="current_item.name"></p>
        </div>
    </div>

    <div ng-include="template_view"></div>

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

</div>
