<div class="sidebar l1" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="page_title" message="message" right-button="header_right_button"></sb-header>

    <div class="subheader sidebar right slide-right" ng-hide="!sidebar.show">
        <div class="content">
            <ul > <!-- ng-click="show_sidebar = false;" -->
                <li ng-repeat="item in sidebar.collection" ng-include="'sidebar_l1.html'"></li>
            </ul>
        </div>
    </div>
    <div class="subheader content">
        <div>
            <h3 class="title" ng-hide="sidebar.is_loading">{{ sidebar.current_item.name }}</h3>
            <p class="small loader" ng-show="sidebar.is_loading"></p>
        </div>
    </div>

    <div class="scrollable_content">
        <div ng-include="template_view"></div>
    </div>

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

</div>

<script type="text/ng-template" id="sidebar_l1.html">

    <a class="item reverse" ng-click="sidebar.showItem(item);" ng-class="{subheader: sidebar.current_item == item}">
        {{ item.name }}
    </a>

    <ul ng-if="item.children" ng-show="item.show_children">
        <li ng-repeat="item in item.children" ng-include="'sidebar_l1.html'"></li>
    </ul>

</script>