<div id="colors_overview" class="iphone_content">
    <iframe id="mobile_overview" src="<?php echo $this->getApplication()->getUrl("application/mobile_customization_colors", array(), true); ?>" width="320" height="1081" style="overflow: hidden;"></iframe>
    <iframe id="homepage_overview" src="<?php echo $this->getApplication()->getUrl("front/mobile_home/colors", array(), true); ?>" width="320" height="460" style="overflow: hidden; display: none;"></iframe>
</div>