<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $facebook = $option_value->getObject(); ?>
<div class="form_content">
    <div id="list" class="edit_page facebook">
        <div class="section form_content">
            <form id="facebookForm" name="facebookForm" method="post" action="<?php echo $this->getUrl('social/application_facebook/editpost') ?>">
                <h4 class="subtitle">
                    <span class="left area"><?php echo $this->_('Facebook') ?></span>
                    <hr class="area reverse">
                    <div class="clear"></div>
                </h4>
                <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
                <div class="form_content">
                    <table class="list" id="facebook_new">
                        <col width="28px" />
                        <col width="350px" />
                        <col width="40px" />
                        <col width="100px" />
                        <tr>
                            <th></th>
                            <th align="left"><?php echo $this->_('Enter your Facebook Fan Page Id <span class="required-entry"> *</span>:') ?></th>
                            <th></th>
                            <th></th>
                        </tr>
                        <tr rel="list_new">
                            <td></td>
                            <td>
                                <input type="text" id="fb_url" name="fb_user" value="<?php echo $facebook->getFbUser()?>" placeholder="<?php echo $this->_("Enter your Facebook Fan Page Id") ?>" class="input required" />
                            </td>
                            <td>
                                <i id="fb_valid_username" class="icon-ok" style="display:none;"></i>
                                <i id="fb_invalid_username" class="icon-remove" style="display:none;"></i>
                                <input type="hidden" name="option_value_id" value="<?php echo $option_value->getId(); ?>" />
                                <input type="hidden" name="id" value="<?php echo $facebook->getId(); ?>" />
                            </td>
                            <td>
                                <div class="save right">
                                    <button class="default_button btn-block" type="submit">
                                        <?php echo $this->_('OK'); ?>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
        <div class="section">
            <?php
            echo $this->getLayout()
                ->addPartial('background_image', 'Core_View_Default', 'application/customization/features/edit/background_image.phtml')
                ->setValueId($option_value->getId())
                ->toHtml()
            ;
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">

    page.setCallback('didappear', function() {

        $('#facebookForm').submit(function() {
            if(!$(this).valid()) return false;
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    iframe.f.page.reload();
                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#facebookForm').unbind('submit');
    });

    background_image.setCallback('cropDidFinish', function() {
        iframe.content.find('.news').addClass('no-background');
        iframe.content.find('.comments').addClass('no-background');
    }).setCallback('imageDidRemove', function(datas) {
        if(!datas.background_image_url) {
            iframe.content.find('.news').removeClass('no-background');
            iframe.content.find('.comments').removeClass('no-background');
        }
    });

</script>