<div class="has_header" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="page_title" message="message"></sb-header>

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

    <div class="event_view">
        <div class="cover" ng-class="{'has-picture': event.cover_image}" ng-hide="event.is_invisible" ng-style="style_cover_image">
            <h3>
                <span class="title block" data-rows="1">{{ event.title }}</span>
                <span class="subtitle" data-rows="1">{{ event.subtitle }}</span>
            </h3>
        </div>

        <div class="padding">
            <div class="description bold" id="event_description">
                <span>{{ event.description }}</span>
            </div>
            <div class="buttons">
                <button class="button icon_left arrow_right" ng-click="openMaps()" ng-show="event.location">
                    <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/marker.png', true), $this->getApplication()->getBlock('button')->getColor()); ?>" width="21" height="21" />
                    <?php echo $this->_('Locate'); ?>
                </button>
                <button class="button icon_left arrow_right" ng-click="openRsvp()" ng-show="event.rsvp">
                    <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/world.png', true), $this->getApplication()->getColor()); ?>" width="21" height="21" />
                    <?php echo $this->_('RSVP'); ?>
                </button>
            </div>
        </div>
    </div>
</div>
