<div sb-background-image value-id="'homepage'" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <sb-loader is-loading="is_loading" has-connection="has_connection"></sb-loader>

    <div id="tabbar_items" class="tabbar_items tabbar l7" ng-class="{'rotate-in': animate_tabbar}" ng-show="tabbar_is_visible">
        <div id="tabbar_background" class="tabbar"></div>
        <div id="tabbar_items" class="tabbar no-background border-color animated toPlayerLeft">

            <ul id="tabbar" class="tabbar_l7">

                <li ng-repeat="option in limited_options" ng-if="option.is_active" class="border-color">
                    <a href="{{ option.url }}" class="item" ng-class="{ is_link: option.is_link }">
                        <img ng-src="{{ option.icon_url }}" ng-class="{ colorable: option.icon_is_colorable }" width="30" height="30" />
                        <span class="block">{{ option.name }}</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>