<?php $android_key = Push_Model_Certificat::getAndroidKey(); ?>
<?php $android_sender_id = Push_Model_Certificat::getAndroidSenderId(); ?>
<?php $ios_certificat_path = Push_Model_Certificat::getiOSCertificat(); ?>
<div class="application_settings application">
    <div class="application_header app_name">
        <?php echo $this->getPartialHtml('customization_header'); ?>
    </div>
    <div class="application_content inner_content">
        <div class="title">
            <i class="left icon-comment"></i>
            <h2 class="left f-rounded"><?php echo $this->_('Push Notifications Settings'); ?></h2>
            <div class="clear"></div>
            <hr class="reverse" />
        </div>

        <div class="area">
            <h3 class="title">
                <span class="left area"><?php echo $this->_('iOS'); ?></span>
                <hr class="area reverse" />
                <div class="clear"></div>
            </h3>
            <div class="area_content">
                <br />
                <table class="no-collapse" cellspacing="10" width="100%">
                    <col width="30%"/>
                    <col width="70%"/>
                    <tr>
                        <td><label for="ios"><?php echo $this->_('Send you .pem certificate'); ?></label></td>
                        <td>
                            <input id="ios_certificat_uploader" type="file" id="ios" name="path" class="input" value="" data-url="<?php echo $this->getUrl('push/certificat/upload'); ?>" />
                            <input type="hidden" name="type" value="iphone" />
                        </td>
                    </tr>
                    <?php if(!empty($ios_certificat_path)) : ?>
                    <tr>
                        <td colspan="2">
                            <?php echo $this->_('You have already sent a certificate'); ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
        <div class="area">
            <h3 class="title">
                <span class="left area"><?php echo $this->_('Android'); ?></span>
                <hr class="area reverse" />
                <div class="clear"></div>
            </h3>
            <div class="area_content">
                <br />
                <table class="no-collapse" cellspacing="10" width="100%">
                    <col width="30%"/>
                    <col width="70%"/>
                    <tr>
                        <td><label for="android_key"><?php echo $this->_('GCM Key'); ?></label></td>
                        <td>
                            <input type="text" id="android_key" name="path" class="save_data input" value="<?php echo $android_key ?>" />
                            <input type="hidden" name="type" value="android_key" />
                        </td>
                    </tr>
                    <tr>
                        <td><label for="android_sender_id"><?php echo $this->_('Sender ID'); ?></label></td>
                        <td>
                            <input type="text" id="android_sender_id" name="path" class="save_data input" value="<?php echo $android_sender_id ?>" />
                            <input type="hidden" name="type" value="android_sender_id" />
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('.save_data').change(function() {
            reload(this.parentNode, '<?php echo $this->getUrl('push/certificat/save'); ?>', true);
        });

        $('#ios_certificat_uploader').fileupload({
            dataType: 'json',
            add: function(e, data) {
//                console.log(data)
                data.submit();
                loader.show();
            },
            done: function(e, data) {
                loader.hide();
                if (data.result.error) {
                    new AlertMessage(data.result.message, true).isError(true).show();
                } else if (data.result.success) {
//                    new AlertMessage(data.result.message_success).isError(false).show();
                    window.location = window.location.href;
                }
            }
        });
    });
</script>
