<?php $option = $this->getCurrentOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $post = $this->getCurrentPost(); ?>
<?php $block_subheader = $application->getBlock('subheader'); ?>
<?php $block_button = $application->getBlock('button'); ?>

<div>
    <div id="scrolview_facebook_post_<?php echo $post->getId() ?>" class="new_details relative comment_details_<?php echo $option->getId(); ?> news<?php if($option->getBackgroundImage()) : ?> _no-background<?php endif; ?>" rel="facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>">
        <ul id="scrolview_details_<?php echo $post->getId(); ?>">
            <li id="comment_details_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>" class="subheader comment_details_title">
                <div id="logo_cont_<?php echo $post->getId(); ?>" class="logo left" style="width:37px; height:37px; overflow:hidden">
                    <img width="37" height="37" id="logo_src_<?php echo $post->getId(); ?>" class="logo_src" src="<?php echo $post->getAvatarUrl() ?>" onload="page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').refreshScrollview(); $(this).removeAttr('onload');" />
                </div>
                <p class="text"><span class="name bold"><?php echo $post->getAuthor(); ?></span></p>
                <p class="text"><span class="name"><?php echo $post->getDetails(); ?></span></p>
                <div class="clear"></div>
                <div class="comment_metas">
                    <span class="comments_date lowercase left">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/pencil.png', true), $block_subheader->getColor()); ?>" alt="" style="vertical-align:bottom" width="13" height="10px"/>
                        <?php echo $post->getCreatedAt() ?>
                    </span>
                    <span class="comments_count right">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/comment.png', true), $block_subheader->getColor()); ?>" alt="<?php echo $this->_('Coms') ?>" style="vertical-align:bottom" width="13" />
                        <?php echo $post->getNbrOfComments() ?>
                    </span>
                    <span class="likes_count right">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/like.png', true), $block_subheader->getColor()); ?>" alt="<?php echo $this->_('Likes') ?>" style="vertical-align:bottom" width="13" height="12px" />
                        <?php echo $post->getNbrOfLikes() ?>
                    </span>
                    <div class="clear"></div>
                </div>
            </li>
            <li class="comment_details_content<?php if($option->getBackgroundImage()) : ?> _no-background<?php endif; ?>">
                <?php if($post->getPicture()) : ?>
                <div class="comment_details_image" style="margin:10px 0;">
                    <img id="comment_details_image_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>" src="<?php echo $post->getPicture() ?>" width="100%" alt="<?php echo $post->getName() ?>" title="<?php echo $post->getName() ?>" onload="page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').refreshScrollview();" <?php if($post->getId() == 'new') : ?> style="display:none;"<?php endif; ?> />
                </div>
                <?php endif; ?>
                <p id="comment_details_text_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>" class="comment_details_text">
                    <?php echo $post->getMessage() ?>
                </p>
            </li>
            <li class="separator"></li>
            <?php if($this->getApplication()->getFacebookId()) : ?>
            <li class="<?php if($option->getBackgroundImage()) : ?>_no-background<?php endif; ?>">
                <div class="padding add_comment">
                    <button type="button" class="button icon_left" onclick="javascript:$('#li_add_comment_<?php echo $post->getId() ?>').slideDown(300, function() {page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').refreshScrollview();});">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/comment.png', true), $block_button->getColor()); ?>" width="25" height="20" />
                        <?php echo $this->_('Comment'); ?>
                    </button>
                    <button type="button" id="like_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>" class="button icon_left" onclick="page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').like($(this).hasClass('liked'))">
                        <img src="<?php echo $this->getColorizedImage($this->getImage('pictos/like.png', true), $block_button->getColor()); ?>" width="25" height="20" />
                        <span><?php echo $this->_('Like'); ?></span>
                    </button>
                </div>
            </li>
            <li id="li_add_comment_<?php echo $post->getId() ?>" rel="<?php echo $post->getId() ?>" class="align-center news<?php if($option->getBackgroundImage()) : ?> _no-background<?php endif; ?>" style="display: none">
                <div class="comment_content padding">
                    <form method="post" action="" onsubmit="page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').post($(this)); return false;">
                        <input type="text" class="message required full_width block" name="message" value="" placeholder="<?php echo $this->_("Your comment") ?>" />
                        <div class="button">
                            <button type="button" id="cancel_comment_<?php echo $post->getId(); ?>" onclick="javascript:$('#li_add_comment_<?php echo $post->getId() ?>').slideUp(300, function() {page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').refreshScrollview();});" class="pad_button cancel left"><?php echo $this->_('Cancel'); ?></button>
                            <button type="submit" id="validate_comment_<?php echo $post->getId(); ?>" class="pad_button validate correct right"><?php echo $this->_('Validate'); ?></button>
                        </div>
                    </form>
                </div>
                <div class="clear"></div>
            </li>
            <?php endif; ?>
            <?php $comments = $post->getComments(); ?>
            <?php foreach($comments as $comment) : ?>
            <li id="answer_<?php echo $comment->getId() ?>" class="comments answer<?php if($option->getBackgroundImage()) : ?> _no-background<?php endif; ?>">
                <div>
                    <?php $customer_name = $comment->getName(); ?>
                    <img width="35" height="35" class="logo left" src="<?php echo $comment->getPicture() ?>" title="<?php echo $customer_name ?>" alt="<?php echo $customer_name ?>" />
                    <p class="text"><span class="bold"><?php echo $customer_name; ?></span> <?php echo $comment->getMessage(); ?></p>
                    <span class="clear left" style="margin-top: 5px;"><?php echo $this->_('Published on %s', $comment->getCreatedAt()); ?></span>
                    <div class="clear"></div>
                </div>
            </li>
            <li class="separator"></li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
<script type="text/javascript">

    var subpage = page.getSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>');

    subpage.setCallback('didcreate', function() {
        facebook.setCallback('didlike', function() {
            $('#like_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').addClass('liked').children('span').html('<?php echo addslashes($this->_('Unlike')); ?>');
        });
        facebook.isLiked('<?php echo $post->getId(); ?>');
        this.unsCallback('didcreate');
    }).setCallback('willappear', function() {
        var scrollview = new iScroll('scrolview_facebook_post_<?php echo $post->getId(); ?>', {
            hScroll: false
        });
        this.setScrollview(scrollview);
    }).setCallback('willdisappear', function() {
        facebook.unsCallback('isauthorized')
            .unsCallback('didpost')
            .unsCallback('didlike')
            .unsCallback('didunlike')
            .unsCallback('datasdidretrieve')
        ;

    }).setCallback('didrefresh', function() {
        facebook.setCallback('didlike', function() {
            $('#like_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>').addClass('liked').children('span').html('<?php echo addslashes($this->_('Unlike')); ?>');
        });
        facebook.isLiked('<?php echo $post->getId(); ?>');
    });

    subpage.post = function(form) {

        if(!form.valid()) return false;

        var post_id = '<?php echo $post->getId(); ?>';
        var message = form.children('input.message').val();
        facebook.setCallback('isauthorized', function() {
            this.post(post_id, message);
        }).setCallback('didpost', function() {
//            form.children('input.message').val('');
            page.refreshSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>');
        });

        facebook.go();
    }

    subpage.like = function(is_liked) {

        var post_id = '<?php echo $post->getId(); ?>'
        var button = $('#like_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>');

        facebook.setCallback('isauthorized', function() {
            if(!is_liked) this.like(post_id);
            else this.unlike(post_id);
        }).setCallback('didlike', function() {
            page.refreshSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>');
//            button.addClass('liked').children('span').html('<?php echo addslashes($this->_('Unlike')); ?>');
        }).setCallback('didunlike', function() {
            page.refreshSubpage('facebook_post_<?php echo $option->getId(); ?>_<?php echo $post->getId(); ?>');
//            button.removeClass('liked').children('span').html('<?php echo addslashes($this->_('Like')); ?>');
        });

        facebook.go();
    }

</script>